### PR TITLE
Added tailwind, made it look normal

### PR DESCRIPTION
**Pull request by shaharhi**

### CODE REVIEW

**Comment by shaharhi** [comment]
Screenshot 2024-03-31 at 10 09 59 AM

**Comment by Chizkiyahu** [comment]
@shaharhi 
thanks for the contribution 
but this brake 
1. dark mode 
2. the graph - not visible 
3. plan table - the marked row and the border 
4. red Disclaimer
Screenshot 2024-03-31 at 10 44 24

**Comment by shaharhi** [comment]
thanks for the feedback i think i fixed most things, please have a look :)

**Comment by Chizkiyahu** [comment]
> thanks for the feedback i think i fixed most things, please have a look :)

that again for the code 
1. is break white mode 
Screenshot 2024-03-31 at 14 07 10
2. is break the "chartContainer" chart is shift to left 
Screenshot 2024-03-31 at 14 05 42

thanks

**Comment by Chizkiyahu** [comment]
@shaharhi 
about the dark mode is my mistake the dark reader was enable 
about the graph i change the library that I am using to chart.js

**Pull request merged**
